// packages/react/src/components/date-picker/date-picker.tsx
'use client'

import * as React from 'react'
import { format } from 'date-fns'
import { Calendar, type CalendarProps, type DateRange, type Matcher } from '../calendar/calendar'
import { DateField } from '../date-field/date-field'
import { TimeField } from '../time-field/time-field'
import { Input, inputVariants } from '../input'
import { Popover, PopoverContent, PopoverTrigger, type PopoverContentProps } from '../popover/popover'
import { buttonVariants } from '../button/button-variants'
import { useFieldRootContext } from '@base-ui/react/internals/field-root-context'
import { cn } from '../../internal/utils'

type DatePickerSize = 'sm' | 'md' | 'lg'
type DatePickerVariant = 'outline' | 'soft'
type DatePickerMode = 'single' | 'range' | 'multiple'

type DistributiveOmit<T, K extends keyof never> = T extends unknown ? Omit<T, K> : never

type CalendarPassthrough = DistributiveOmit<
  CalendarProps,
  | 'mode'
  | 'selected'
  | 'onSelect'
  | 'month'
  | 'onMonthChange'
  | 'size'
  | 'classNames'
  | 'components'
  | 'className'
  | 'disabled'
>

type DatePickerBase = CalendarPassthrough & {
  /**
   * Height, padding, and calendar cell scale.
   * @default 'md'
   */
  size?: DatePickerSize
  /**
   * Field appearance - bordered or filled.
   * @default 'outline'
   */
  variant?: DatePickerVariant
  /**
   * date-fns format for the date field(s).
   * @default 'MM/dd/yyyy'
   */
  dateFormat?: string
  /**
   * date-fns format for the time field(s).
   * @default 'HH:mm:ss'
   */
  timeFormat?: string
  /**
   * Show a clear button (multiple mode).
   * @default false
   */
  clearable?: boolean
  /** Content pinned to the start edge. */
  startSlot?: React.ReactNode
  /** Content pinned to the end edge. */
  endSlot?: React.ReactNode
  /**
   * Disable the whole control.
   * @default false
   */
  disabled?: boolean
  /** Dates that can't be selected in the calendar. */
  disabledDates?: Matcher | Matcher[]
  /**
   * Make the typeable fields read-only.
   * @default false
   */
  readOnly?: boolean
  /**
   * Mark the form field as required.
   * @default false
   */
  required?: boolean
  /**
   * Hidden input name for form submission. `range` mode emits `name[from]` / `name[to]`; with `showTime` the value is a
   * full datetime.
   */
  name?: string
  /** Flag the field invalid - sets `data-invalid` for styling + conveys it to assistive tech. */
  'aria-invalid'?: boolean
  /** Classes on the root wrapper - use for footprint/layout (e.g. `max-w-60`). Merged via `tailwind-merge`. */
  className?: string
  /**
   * Classes on the inner field box - use to override field styling (border, radius, background). Merged via
   * `tailwind-merge`.
   */
  inputClassName?: string
  /**
   * Separator between the range's two fields.
   * @default '–'
   */
  rangeSeparator?: React.ReactNode
  /** Controlled open state. Pair with `onOpenChange`. */
  open?: boolean
  /**
   * Uncontrolled initial open state.
   * @default false
   */
  defaultOpen?: boolean
  /** Fires when the popover opens or closes. */
  onOpenChange?: (open: boolean) => void
  /**
   * Preferred popover side.
   * @default 'bottom'
   */
  side?: 'top' | 'bottom' | 'left' | 'right'
  /**
   * Popover alignment.
   * @default 'end'
   */
  align?: 'start' | 'center' | 'end'
  /**
   * Gap between the field and the popover.
   * @default 6
   */
  sideOffset?: number
  /** Escape hatch forwarded to the inner `PopoverContent` (collision props, `className`, …). */
  popoverProps?: Partial<PopoverContentProps>
  /**
   * Override auto-close. By default only single mode closes on pick; range and multiple stay open (dismiss on
   * outside-click/Escape).
   * @default auto
   */
  closeOnSelect?: boolean
  /**
   * Add a `TimeField` (single/range modes).
   * @default false
   */
  showTime?: boolean
  /**
   * Icon for the popover trigger button.
   * @default calendar icon
   */
  triggerIcon?: React.ReactNode
  /**
   * Accessible label for the trigger button.
   * @default 'Open calendar'
   */
  triggerAriaLabel?: string
}

type DatePickerProps =
  | (DatePickerBase & {
      mode?: 'single'
      value?: Date | undefined
      defaultValue?: Date | undefined
      onValueChange?: (v: Date | undefined) => void
    })
  | (DatePickerBase & {
      mode: 'range'
      value?: DateRange | undefined
      defaultValue?: DateRange | undefined
      onValueChange?: (v: DateRange | undefined) => void
    })
  | (DatePickerBase & {
      /**
       * Selection behavior; determines the `value` shape.
       * @default 'single'
       */
      mode: 'multiple'
      /** Controlled value; shape matches `mode`. Pair with `onValueChange`. */
      value?: Date[] | undefined
      /** Uncontrolled initial value. */
      defaultValue?: Date[] | undefined
      /** Fires when the selection changes; the argument shape matches `mode`. */
      onValueChange?: (v: Date[] | undefined) => void
      /** Placeholder for the multiple-mode summary field. */
      placeholder?: string
      /** Customize the multiple-mode summary text. */
      formatValue?: (value: Date[] | undefined) => string
    })

const DEFAULT_TRIGGER_ICON = (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18" fill="currentColor" aria-hidden="true">
    <path d="M14.425 8.825H3.575v5.425c0 .245.097.481.27.654s.409.271.654.271h9c.245 0 .481-.097.654-.271s.271-.409.271-.654V8.825zm-9.163 3.35c.317 0 .574.258.574.575s-.257.575-.574.575h-.004c-.318 0-.575-.258-.575-.575s.258-.575.575-.575h.004zm2.25 0c.317 0 .574.258.574.575s-.257.575-.574.575h-.004c-.318 0-.575-.258-.575-.575s.258-.575.575-.575h.004zm2.253 0c.318 0 .575.258.575.575s-.258.575-.575.575h-.003c-.318 0-.575-.258-.575-.575s.258-.575.575-.575h.003zM5.26 9.925c.318 0 .575.258.575.575s-.258.575-.575.575h-.01c-.318 0-.575-.258-.575-.575s.258-.575.575-.575h.01zm2.252 0c.317 0 .574.258.574.575s-.257.575-.574.575h-.004c-.318 0-.575-.258-.575-.575s.258-.575.575-.575h.004zm2.25 0c.317 0 .574.258.574.575s-.257.575-.574.575h-.004c-.318 0-.575-.258-.575-.575s.258-.575.575-.575h.004zm2.253 0c.318 0 .575.258.575.575s-.258.575-.575.575h-.003c-.317 0-.575-.258-.575-.575s.258-.575.575-.575h.003zm-.59-4.675v-.925h-4.85v.925c0 .318-.258.575-.575.575s-.575-.258-.575-.575v-.925H4.5c-.245 0-.481.097-.654.271s-.27.409-.27.654v2.425h10.85V5.25c0-.245-.097-.481-.271-.654s-.409-.271-.654-.271h-.925v.925c0 .318-.258.575-.575.575s-.575-.258-.575-.575zm4.15 9c0 .55-.219 1.078-.608 1.467s-.916.608-1.467.608h-9c-.55 0-1.078-.219-1.467-.608s-.608-.916-.608-1.467v-9c0-.55.219-1.078.608-1.467s.916-.608 1.467-.608h.925V2.25c0-.318.258-.575.575-.575s.575.258.575.575v.925h4.85V2.25c0-.318.258-.575.575-.575s.575.258.575.575v.925h.925c.55 0 1.078.219 1.467.608s.608.916.608 1.467v9z" />
  </svg>
)

const TRIGGER_BUTTON_OVERRIDES: Record<DatePickerSize, string> = {
  sm: 'size-6 rounded-xs -me-1.25',
  md: 'size-8 rounded-sm -me-1.75',
  lg: 'size-10 rounded-md -me-2.25',
}

const TRIGGER_BUTTON_SIZES: Record<DatePickerSize, 'icon-sm' | 'icon-md' | 'icon-lg'> = {
  sm: 'icon-sm',
  md: 'icon-md',
  lg: 'icon-lg',
}

function DatePicker(props: DatePickerProps) {
  const {
    size = 'md',
    mode = 'single',
    variant = 'outline',
    value,
    defaultValue,
    onValueChange,
    open,
    defaultOpen,
    onOpenChange,
    showTime = false,
    dateFormat = 'MM/dd/yyyy',
    timeFormat = 'HH:mm:ss',
    placeholder,
    clearable,
    startSlot,
    endSlot,
    disabled: disabledProp,
    disabledDates,
    readOnly,
    required,
    name: nameProp,
    side = 'bottom',
    align = 'end',
    sideOffset = 6,
    popoverProps,
    closeOnSelect,
    rangeSeparator = '–',
    triggerIcon = DEFAULT_TRIGGER_ICON,
    triggerAriaLabel = 'Open calendar',
    formatValue,
    'aria-invalid': _ariaInvalid,
    className,
    inputClassName,
    ...calendarProps
  } = props as DatePickerBase & {
    mode?: DatePickerMode
    value?: Date | Date[] | DateRange
    defaultValue?: Date | Date[] | DateRange
    onValueChange?: (v: unknown) => void
    placeholder?: string
    formatValue?: (value: Date[] | undefined) => string
  }

  const field = useFieldRootContext(true)
  const disabled = disabledProp || field.disabled
  const name = nameProp ?? field.name
  const invalid = props['aria-invalid'] === true || field.invalid === true

  const wasControlledRef = React.useRef(value !== undefined)
  if (value !== undefined) wasControlledRef.current = true
  const isValueControlled = wasControlledRef.current
  const [internalValue, setInternalValue] = React.useState<Date | Date[] | DateRange | undefined>(defaultValue)
  const currentValue = isValueControlled ? value : internalValue

  const isOpenControlled = open !== undefined
  const [internalOpen, setInternalOpen] = React.useState(defaultOpen ?? false)
  const currentOpen = isOpenControlled ? open : internalOpen

  const [calendarMonth, setCalendarMonth] = React.useState<Date | undefined>(() => {
    const fromValue = deriveCalendarMonth(mode, defaultValue ?? value)
    if (fromValue) return fromValue
    return (calendarProps as { defaultMonth?: Date }).defaultMonth
  })

  const derivedMonth = deriveCalendarMonth(mode, currentValue)
  const lastDerivedKeyRef = React.useRef<string>(monthKey(derivedMonth))
  React.useEffect(() => {
    const key = monthKey(derivedMonth)
    if (key !== lastDerivedKeyRef.current) {
      lastDerivedKeyRef.current = key
      if (derivedMonth) setCalendarMonth(derivedMonth)
    }
  }, [derivedMonth])

  const setOpen = React.useCallback(
    (next: boolean) => {
      if (!isOpenControlled) setInternalOpen(next)
      onOpenChange?.(next)
    },
    [isOpenControlled, onOpenChange],
  )

  const setValue = React.useCallback(
    (next: Date | Date[] | DateRange | undefined) => {
      if (!isValueControlled) setInternalValue(next)
      onValueChange?.(next)
      if (shouldAutoClose(mode, next, closeOnSelect)) setOpen(false)
    },
    [isValueControlled, mode, closeOnSelect, onValueChange, setOpen],
  )

  const handleDateFieldChange = (nextDate: Date | null) => {
    if (mode !== 'single') return
    if (!nextDate) {
      setValue(undefined)
      return
    }
    setValue(mergeDateAndTime(nextDate, currentValue as Date | undefined))
  }

  const handleTimeFieldChange = (nextTime: string | null) => {
    if (mode !== 'single' || !showTime) return
    const cur = currentValue as Date | undefined
    if (!cur) return
    setValue(applyTimeString(cur, nextTime))
  }

  const handleRangeFromDateChange = (nextDate: Date | null) => {
    if (mode !== 'range') return
    const cur = currentValue as DateRange | undefined
    const merged = nextDate ? mergeDateAndTime(nextDate, cur?.from) : undefined
    setValue({ from: merged, to: cur?.to })
  }

  const handleRangeToDateChange = (nextDate: Date | null) => {
    if (mode !== 'range') return
    const cur = currentValue as DateRange | undefined
    const merged = nextDate ? mergeDateAndTime(nextDate, cur?.to) : undefined
    setValue({ from: cur?.from, to: merged })
  }

  const handleRangeFromTimeChange = (nextTime: string | null) => {
    if (mode !== 'range' || !showTime) return
    const cur = currentValue as DateRange | undefined
    if (!cur?.from) return
    setValue({ from: applyTimeString(cur.from, nextTime), to: cur.to })
  }

  const handleRangeToTimeChange = (nextTime: string | null) => {
    if (mode !== 'range' || !showTime) return
    const cur = currentValue as DateRange | undefined
    if (!cur?.to) return
    setValue({ from: cur.from, to: applyTimeString(cur.to, nextTime) })
  }

  const handleCalendarSelect = (nextRaw: Date | Date[] | DateRange | undefined) => {
    if (mode === 'single' && nextRaw instanceof Date) {
      setValue(mergeDateAndTime(nextRaw, currentValue as Date | undefined))
    } else if (mode === 'range' && nextRaw && !(nextRaw instanceof Date) && !Array.isArray(nextRaw)) {
      const cur = currentValue as DateRange | undefined
      const r = nextRaw as DateRange
      setValue({
        from: r.from ? mergeDateAndTime(r.from, cur?.from) : undefined,
        to: r.to ? mergeDateAndTime(r.to, cur?.to) : undefined,
      })
    } else {
      setValue(nextRaw)
    }
  }

  const clearAll = React.useCallback(() => setValue(undefined), [setValue])

  const anchorRef = React.useRef<HTMLDivElement>(null)

  const triggerButton = (
    <PopoverTrigger
      disabled={disabled}
      render={(triggerProps) => (
        <button
          {...(triggerProps as unknown as React.ButtonHTMLAttributes<HTMLButtonElement>)}
          type="button"
          aria-label={triggerAriaLabel}
          className={cn(
            buttonVariants({ variant: 'ghost', size: TRIGGER_BUTTON_SIZES[size] }),
            TRIGGER_BUTTON_OVERRIDES[size],
            'text-foreground',
          )}
        >
          {triggerIcon}
        </button>
      )}
    />
  )

  const sharedFieldProps = {
    variant,
    size,
    disabled,
    readOnly,
    required,
    'aria-invalid': invalid || undefined,
  } as const

  let fields: React.ReactNode

  if (mode === 'single') {
    const date = currentValue as Date | undefined
    if (showTime) {
      fields = (
        <UnifiedWrapper
          variant={variant}
          size={size}
          disabled={disabled}
          ariaInvalid={invalid || undefined}
          className={inputClassName}
          startSlot={startSlot}
          endSlot={endSlot}
          trigger={triggerButton}
        >
          <DateField
            unstyled
            value={date ?? null}
            onValueChange={handleDateFieldChange}
            format={dateFormat}
            {...sharedFieldProps}
          />
          <TimeField
            unstyled
            value={date ? format(date, 'HH:mm:ss') : null}
            onValueChange={handleTimeFieldChange}
            format={timeFormat}
            {...sharedFieldProps}
          />
        </UnifiedWrapper>
      )
    } else {
      fields = (
        <DateField
          value={date ?? null}
          onValueChange={handleDateFieldChange}
          format={dateFormat}
          startSlot={startSlot}
          endSlot={
            <>
              {endSlot}
              {triggerButton}
            </>
          }
          className={inputClassName}
          {...sharedFieldProps}
        />
      )
    }
  } else if (mode === 'range') {
    const range = currentValue as DateRange | undefined
    fields = (
      <UnifiedWrapper
        variant={variant}
        size={size}
        disabled={disabled}
        ariaInvalid={invalid || undefined}
        className={inputClassName}
        startSlot={startSlot}
        endSlot={endSlot}
        trigger={triggerButton}
      >
        <DateField
          unstyled
          value={range?.from ?? null}
          onValueChange={handleRangeFromDateChange}
          format={dateFormat}
          {...sharedFieldProps}
        />
        {showTime && (
          <TimeField
            unstyled
            value={range?.from ? format(range.from, 'HH:mm:ss') : null}
            onValueChange={handleRangeFromTimeChange}
            format={timeFormat}
            {...sharedFieldProps}
          />
        )}
        <span className="text-foreground-muted shrink-0" aria-hidden="true">
          {rangeSeparator}
        </span>
        <DateField
          unstyled
          value={range?.to ?? null}
          onValueChange={handleRangeToDateChange}
          format={dateFormat}
          {...sharedFieldProps}
        />
        {showTime && (
          <TimeField
            unstyled
            value={range?.to ? format(range.to, 'HH:mm:ss') : null}
            onValueChange={handleRangeToTimeChange}
            format={timeFormat}
            {...sharedFieldProps}
          />
        )}
      </UnifiedWrapper>
    )
  } else {
    const days = currentValue as Date[] | undefined
    const display = formatValue ? formatValue(days) : defaultMultipleFormat(days, dateFormat)
    fields = (
      <Input
        inputSize={size}
        variant={variant}
        value={display}
        readOnly
        placeholder={placeholder}
        clearable={clearable && (days?.length ?? 0) > 0}
        onClear={clearAll}
        startSlot={startSlot}
        endSlot={
          <>
            {endSlot}
            {triggerButton}
          </>
        }
        disabled={disabled}
        required={required}
        name={name}
        aria-invalid={invalid || undefined}
        className={inputClassName}
      />
    )
  }

  let hiddenInputs: React.ReactNode = null
  if (name && mode === 'single') {
    hiddenInputs = <input type="hidden" name={name} value={toFormValue(currentValue as Date | undefined, showTime)} />
  } else if (name && mode === 'range') {
    const r = currentValue as DateRange | undefined
    hiddenInputs = (
      <>
        <input type="hidden" name={`${name}[from]`} value={toFormValue(r?.from ?? undefined, showTime)} />
        <input type="hidden" name={`${name}[to]`} value={toFormValue(r?.to ?? undefined, showTime)} />
      </>
    )
  }

  return (
    <Popover open={currentOpen} onOpenChange={setOpen}>
      <div ref={anchorRef} data-slot="date-picker-anchor" className={cn('flex w-full', className)}>
        {fields}
        {hiddenInputs}
      </div>
      <PopoverContent
        side={side}
        align={align}
        sideOffset={sideOffset}
        arrow={false}
        {...popoverProps}
        anchor={anchorRef}
        className={cn('w-fit max-w-none min-w-0 p-3', popoverProps?.className)}
      >
        <Calendar
          size={size}
          mode={mode as never}
          selected={currentValue as never}
          onSelect={handleCalendarSelect as never}
          {...(calendarProps as Record<string, unknown>)}
          month={calendarMonth}
          onMonthChange={setCalendarMonth}
          disabled={disabledDates}
        />
      </PopoverContent>
    </Popover>
  )
}

interface UnifiedWrapperProps {
  variant: DatePickerVariant
  size: DatePickerSize
  disabled?: boolean
  ariaInvalid?: boolean
  className?: string
  startSlot?: React.ReactNode
  endSlot?: React.ReactNode
  trigger: React.ReactNode
  children: React.ReactNode
}

function UnifiedWrapper({
  variant,
  size,
  disabled,
  ariaInvalid,
  className,
  startSlot,
  endSlot,
  trigger,
  children,
}: UnifiedWrapperProps) {
  return (
    <div
      data-slot="date-picker"
      data-disabled={disabled || undefined}
      data-invalid={ariaInvalid || undefined}
      className={cn(
        inputVariants({ variant, size, state: 'within' }),
        'flex w-full',
        'data-disabled:border-border-strong! data-disabled:bg-background-subtle! data-disabled:opacity-disabled data-disabled:pointer-events-none data-disabled:cursor-not-allowed data-disabled:border-dashed',
        className,
      )}
    >
      {startSlot ? (
        <div data-slot="date-picker-start" className="-ms-1 shrink-0">
          {startSlot}
        </div>
      ) : null}
      {children}
      {endSlot ? (
        <div data-slot="date-picker-end" className="shrink-0">
          {endSlot}
        </div>
      ) : null}
      <div data-slot="date-picker-trigger" className="ms-auto -me-1 shrink-0">
        {trigger}
      </div>
    </div>
  )
}

function shouldAutoClose(
  mode: DatePickerMode,
  next: Date | Date[] | DateRange | undefined,
  override?: boolean,
): boolean {
  if (override !== undefined) return override
  if (mode === 'single') return next instanceof Date
  return false
}

function mergeDateAndTime(nextDate: Date, withTime: Date | undefined): Date {
  if (!withTime) return nextDate
  const out = new Date(nextDate)
  out.setHours(withTime.getHours(), withTime.getMinutes(), withTime.getSeconds(), withTime.getMilliseconds())
  return out
}

function toFormValue(date: Date | undefined, showTime: boolean): string {
  if (!date) return ''
  return format(date, showTime ? "yyyy-MM-dd'T'HH:mm:ss" : 'yyyy-MM-dd')
}

function applyTimeString(base: Date, timeStr: string | null): Date {
  const out = new Date(base)
  if (!timeStr) {
    out.setHours(0, 0, 0, 0)
    return out
  }
  const [h, m, s] = timeStr.split(':').map((n) => Number(n) || 0)
  out.setHours(h ?? 0, m ?? 0, s ?? 0, 0)
  return out
}

function deriveCalendarMonth(mode: DatePickerMode, value: Date | Date[] | DateRange | undefined): Date | undefined {
  if (!value) return undefined
  if (mode === 'single') return value instanceof Date ? value : undefined
  if (mode === 'range') {
    const r = value as DateRange
    return r.from ?? r.to ?? undefined
  }
  if (mode === 'multiple') {
    const days = value as Date[]
    return days[days.length - 1]
  }
  return undefined
}

function monthKey(d: Date | undefined): string {
  if (!d) return ''
  return `${d.getFullYear()}-${d.getMonth()}`
}

function defaultMultipleFormat(days: Date[] | undefined, dateFormat: string): string {
  if (!days || days.length === 0) return ''
  const first = format(days[0]!, dateFormat)
  return days.length === 1 ? first : `${first} (+${days.length - 1} more)`
}

export { DatePicker }
export type { DatePickerProps, DateRange }

// packages/svelte/src/components/date-picker/date-picker.svelte
<script lang="ts" module>
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  import type { DateValue } from '@internationalized/date'
  import type { TimeValue } from 'bits-ui'
  import type { CalendarSize, CalendarMode, DateRange } from '../calendar/calendar-tokens'
  import type { DateFieldVariant } from '../date-field/date-field.svelte'

  export type DatePickerSize = CalendarSize
  export type DatePickerVariant = DateFieldVariant
  export type DatePickerType = CalendarMode
  export type { DateRange }

  type WeekStartsOn = 0 | 1 | 2 | 3 | 4 | 5 | 6
  type Side = 'top' | 'bottom' | 'left' | 'right'
  type Align = 'start' | 'center' | 'end'

  export type DatePickerProps = Omit<HTMLAttributes<HTMLDivElement>, 'children'> & {
    /**
     * Height, padding, and calendar cell scale.
     * @default 'md'
     */
    size?: DatePickerSize
    /**
     * Selection behavior. `range` uses a start/end pair.
     * @default 'single'
     */
    type?: DatePickerType
    /**
     * Field appearance - bordered or filled.
     * @default 'outline'
     */
    variant?: DatePickerVariant
    /** Controlled value. Shape matches `type`. Pair with `onValueChange` or `bind:value`. */
    value?: DateValue | DateValue[] | DateRange
    /** Uncontrolled initial value. */
    defaultValue?: DateValue | DateValue[] | DateRange
    /** Fires when the selection changes. The argument shape matches `type`. */
    onValueChange?: (value: DateValue | DateValue[] | DateRange | undefined) => void
    /** Controlled open state. Pair with `onOpenChange` or `bind:open`. */
    open?: boolean
    /**
     * Uncontrolled initial open state.
     * @default false
     */
    defaultOpen?: boolean
    /** Fires when the popover opens or closes. */
    onOpenChange?: (open: boolean) => void
    /**
     * Add a `TimeField` (single and range types).
     * @default false
     */
    showTime?: boolean
    /**
     * Show a clear button (multiple type).
     * @default false
     */
    clearable?: boolean
    /** Adornment rendered before the field(s), inside the frame. */
    start?: Snippet
    /** Adornment rendered after the field(s), inside the frame. */
    end?: Snippet
    disabled?: boolean
    readonly?: boolean
    required?: boolean
    name?: string
    /**
     * Separator between the range's two fields.
     * @default '-'
     */
    rangeSeparator?: string
    /**
     * Preferred popover side.
     * @default 'bottom'
     */
    side?: Side
    /**
     * Popover alignment.
     * @default 'end'
     */
    align?: Align
    /**
     * Gap between the field and the popover.
     * @default 6
     */
    sideOffset?: number
    /** Extra props forwarded to `PopoverContent` (`class`, `keepMounted`, …). */
    popoverProps?: { class?: string; keepMounted?: boolean; [key: string]: unknown }
    /**
     * Override auto-close. By default only single type closes on pick; range and multiple stay open.
     */
    closeOnSelect?: boolean
    /** Icon rendered inside the calendar trigger button. */
    triggerIcon?: Snippet
    /**
     * Accessible label for the trigger button.
     * @default 'Open calendar'
     */
    triggerAriaLabel?: string
    /** Placeholder for the multiple-type summary field. */
    placeholder?: string
    /** Customize the multiple-type summary text. */
    formatValue?: (value: DateValue[] | undefined) => string
    /** Visible month when the calendar opens, if no value is selected. */
    defaultPlaceholder?: DateValue
    /** Locale used to format field segments and the calendar. */
    locale?: string
    /**
     * First day of the week. `0` is Sunday, `1` is Monday.
     * @default 1
     */
    weekStartsOn?: WeekStartsOn
    minValue?: DateValue
    maxValue?: DateValue
    fixedWeeks?: boolean
    isDateDisabled?: (date: DateValue) => boolean
    isDateUnavailable?: (date: DateValue) => boolean
    /**
     * 12-hour or 24-hour clock when `showTime` is set.
     */
    hourCycle?: 12 | 24
    /** Classes on the inner field box. */
    inputClassName?: string
  }
</script>

<script lang="ts">
  import { Time, toCalendarDate, toCalendarDateTime } from '@internationalized/date'
  import { untrack } from 'svelte'
  import { cn, commitBindableChange } from '../../internal/utils'
  import { buttonVariants } from '../button/button-variants'
  import Calendar from '../calendar/calendar.svelte'
  import DateField from '../date-field/date-field.svelte'
  import { getFieldContext, mergeFieldControl } from '../field/field-context'
  import Input from '../input/input.svelte'
  import { inputVariants } from '../input/input-variants'
  import { Popover, PopoverContent, PopoverTrigger } from '../popover'
  import TimeField from '../time-field/time-field.svelte'

  const TRIGGER_BUTTON_OVERRIDES: Record<DatePickerSize, string> = {
    sm: 'size-6 rounded-xs -me-1.25',
    md: 'size-8 rounded-sm -me-1.75',
    lg: 'size-10 rounded-md -me-2.25',
  }

  const TRIGGER_BUTTON_SIZES: Record<DatePickerSize, 'icon-sm' | 'icon-md' | 'icon-lg'> = {
    sm: 'icon-sm',
    md: 'icon-md',
    lg: 'icon-lg',
  }

  function isRange(value: unknown): value is DateRange {
    return typeof value === 'object' && value !== null && !Array.isArray(value) && 'from' in value
  }

  function isDateValue(value: unknown): value is DateValue {
    return typeof value === 'object' && value !== null && !Array.isArray(value) && 'year' in value && 'month' in value
  }

  function toTimeValue(value: DateValue | undefined): Time | undefined {
    if (!value) return undefined
    if ('hour' in value) {
      return new Time(value.hour, value.minute, value.second, value.millisecond)
    }
    return new Time(0, 0)
  }

  function mergeDateAndTime(nextDate: DateValue, withTime: DateValue | TimeValue | undefined, withClock: boolean): DateValue {
    if (!withClock) return toCalendarDate(nextDate)
    const time =
      withTime && 'hour' in withTime
        ? new Time(withTime.hour, withTime.minute, withTime.second, withTime.millisecond)
        : new Time(0, 0)
    return toCalendarDateTime(toCalendarDate(nextDate), time)
  }

  function applyTime(base: DateValue | undefined, time: TimeValue | undefined): DateValue | undefined {
    if (!base) return undefined
    if (!time) return toCalendarDate(base)
    return toCalendarDateTime(toCalendarDate(base), new Time(time.hour, time.minute, time.second, time.millisecond))
  }

  function toFormValue(date: DateValue | undefined, withClock: boolean): string {
    if (!date) return ''
    if (!withClock) return toCalendarDate(date).toString()
    const time = toTimeValue(date) ?? new Time(0, 0)
    const hour = String(time.hour).padStart(2, '0')
    const minute = String(time.minute).padStart(2, '0')
    const second = String(time.second).padStart(2, '0')
    return `${toCalendarDate(date).toString()}T${hour}:${minute}:${second}`
  }

  function derivePlaceholder(
    selection: DatePickerType,
    next: DateValue | DateValue[] | DateRange | undefined,
    fallback?: DateValue,
  ): DateValue | undefined {
    if (selection === 'single' && isDateValue(next)) return toCalendarDate(next)
    if (selection === 'range' && isRange(next)) {
      const date = next.from ?? next.to
      if (date) return toCalendarDate(date)
    }
    if (selection === 'multiple' && Array.isArray(next) && next.length > 0) {
      return toCalendarDate(next[next.length - 1]!)
    }
    return fallback
  }

  function monthKey(date: DateValue | undefined): string {
    if (!date) return ''
    return `${date.year}-${date.month}`
  }

  function defaultMultipleFormat(days: DateValue[] | undefined): string {
    if (!days?.length) return ''
    const first = toCalendarDate(days[0]!).toString()
    if (days.length === 1) return first
    return `${first} (+${days.length - 1} more)`
  }

  function shouldAutoClose(
    selection: DatePickerType,
    next: DateValue | DateValue[] | DateRange | undefined,
    override?: boolean,
  ): boolean {
    if (override !== undefined) return override
    if (selection === 'single') return isDateValue(next)
    return false
  }

  let {
    class: className,
    size = 'md',
    type = 'single',
    variant = 'outline',
    value = $bindable(),
    defaultValue,
    onValueChange,
    open = $bindable(),
    defaultOpen = false,
    onOpenChange,
    showTime = false,
    clearable = false,
    start,
    end,
    disabled,
    readonly,
    required,
    name,
    rangeSeparator = '-',
    side = 'bottom',
    align = 'end',
    sideOffset = 6,
    popoverProps,
    closeOnSelect,
    triggerIcon,
    triggerAriaLabel = 'Open calendar',
    placeholder,
    formatValue,
    defaultPlaceholder,
    locale,
    weekStartsOn = 1,
    minValue,
    maxValue,
    fixedWeeks = false,
    isDateDisabled,
    isDateUnavailable,
    hourCycle,
    inputClassName,
    id,
    'aria-invalid': ariaInvalid,
    'aria-describedby': ariaDescribedby,
    'aria-label': ariaLabel,
    'aria-labelledby': ariaLabelledby,
    ...rest
  }: DatePickerProps = $props()

  const field = getFieldContext()
  const control = $derived(
    mergeFieldControl({
      field,
      id,
      name,
      disabled,
      ariaInvalid,
      ariaDescribedby,
      omitId: true,
    }),
  )

  const labelledBy = $derived([ariaLabelledby, field?.labelId].filter(Boolean).join(' ') || undefined)

  let inner = $state<DateValue | DateValue[] | DateRange | undefined>(undefined)
  inner = untrack(() => value ?? defaultValue)

  let innerOpen = $state(false)
  innerOpen = untrack(() => open ?? defaultOpen)

  let calendarPlaceholder = $state<DateValue | undefined>(undefined)
  calendarPlaceholder = untrack(() => derivePlaceholder(type, value ?? defaultValue, defaultPlaceholder))
  let lastDerivedKey = untrack(() => monthKey(calendarPlaceholder))

  $effect(() => {
    if (value !== undefined) inner = value
  })

  $effect(() => {
    if (open !== undefined) innerOpen = open
  })

  const current = $derived(value !== undefined ? value : inner)

  $effect(() => {
    const derived = derivePlaceholder(type, current)
    const key = monthKey(derived)
    if (key && key !== lastDerivedKey) {
      lastDerivedKey = key
      calendarPlaceholder = derived
    }
  })

  function setOpen(next: boolean) {
    commitBindableChange({
      next,
      bound: open,
      setBound: (bound) => {
        open = bound
      },
      setInner: (bound) => {
        innerOpen = bound
      },
      onChange: onOpenChange,
    })
  }

  function setValue(next: DateValue | DateValue[] | DateRange | undefined) {
    commitBindableChange({
      next,
      bound: value,
      setBound: (bound) => {
        value = bound
      },
      setInner: (bound) => {
        inner = bound
      },
      onChange: onValueChange,
    })
    if (shouldAutoClose(type, next, closeOnSelect)) setOpen(false)
  }

  function handleDateFieldChange(nextDate: DateValue | undefined) {
    if (type !== 'single') return
    if (!nextDate) {
      setValue(undefined)
      return
    }
    const cur = isDateValue(current) ? current : undefined
    setValue(mergeDateAndTime(nextDate, cur, showTime))
  }

  function handleTimeFieldChange(nextTime: TimeValue | undefined) {
    if (type !== 'single' || !showTime) return
    const cur = isDateValue(current) ? current : undefined
    if (!cur) return
    setValue(applyTime(cur, nextTime))
  }

  function handleRangeFromDateChange(nextDate: DateValue | undefined) {
    if (type !== 'range') return
    const cur = isRange(current) ? current : undefined
    setValue({
      from: nextDate ? mergeDateAndTime(nextDate, cur?.from, showTime) : undefined,
      to: cur?.to,
    })
  }

  function handleRangeToDateChange(nextDate: DateValue | undefined) {
    if (type !== 'range') return
    const cur = isRange(current) ? current : undefined
    setValue({
      from: cur?.from,
      to: nextDate ? mergeDateAndTime(nextDate, cur?.to, showTime) : undefined,
    })
  }

  function handleRangeFromTimeChange(nextTime: TimeValue | undefined) {
    if (type !== 'range' || !showTime) return
    const cur = isRange(current) ? current : undefined
    if (!cur?.from) return
    setValue({ from: applyTime(cur.from, nextTime), to: cur.to })
  }

  function handleRangeToTimeChange(nextTime: TimeValue | undefined) {
    if (type !== 'range' || !showTime) return
    const cur = isRange(current) ? current : undefined
    if (!cur?.to) return
    setValue({ from: cur.from, to: applyTime(cur.to, nextTime) })
  }

  function handleCalendarSelect(next: DateValue | DateValue[] | DateRange | undefined) {
    if (type === 'single') {
      if (!isDateValue(next)) {
        setValue(undefined)
        return
      }
      const cur = isDateValue(current) ? current : undefined
      setValue(mergeDateAndTime(next, cur, showTime))
      return
    }
    if (type === 'range') {
      if (next !== undefined && !isRange(next)) return
      const cur = isRange(current) ? current : undefined
      setValue({
        from: next?.from ? mergeDateAndTime(next.from, cur?.from, showTime) : undefined,
        to: next?.to ? mergeDateAndTime(next.to, cur?.to, showTime) : undefined,
      })
      return
    }
    setValue(Array.isArray(next) ? next : undefined)
  }

  function handlePlaceholderChange(next: DateValue) {
    lastDerivedKey = monthKey(next)
    calendarPlaceholder = next
  }

  const singleDate = $derived(type === 'single' && isDateValue(current) ? current : undefined)
  const rangeValue = $derived(type === 'range' && isRange(current) ? current : undefined)
  const multipleDays = $derived(type === 'multiple' && Array.isArray(current) ? current : undefined)
  const multipleDisplay = $derived(
    type === 'multiple' ? (formatValue ? formatValue(multipleDays) : defaultMultipleFormat(multipleDays)) : '',
  )

  const wrapperClass = $derived(
    cn(
      inputVariants({ variant, size, state: 'within' }),
      'flex w-full',
      'data-disabled:border-border-strong! data-disabled:bg-background-subtle! data-disabled:opacity-disabled data-disabled:pointer-events-none data-disabled:cursor-not-allowed data-disabled:border-dashed',
      inputClassName,
    ),
  )

  const emitHidden = $derived(Boolean(control.name) && (type === 'range' || (type === 'single' && showTime)))
  const popoverClassName = $derived(typeof popoverProps?.class === 'string' ? popoverProps.class : undefined)
  const popoverKeepMounted = $derived(popoverProps?.keepMounted === true)
  const popoverRest = $derived.by(() => {
    if (!popoverProps) return {}
    const { class: _className, keepMounted: _keepMounted, ...restProps } = popoverProps
    return restProps
  })
</script>

{#snippet defaultTriggerIcon()}
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18" fill="currentColor" aria-hidden="true">
    <path
      d="M14.425 8.825H3.575v5.425c0 .245.097.481.27.654s.409.271.654.271h9c.245 0 .481-.097.654-.271s.271-.409.271-.654V8.825zm-9.163 3.35c.317 0 .574.258.574.575s-.257.575-.574.575h-.004c-.318 0-.575-.258-.575-.575s.258-.575.575-.575h.004zm2.25 0c.317 0 .574.258.574.575s-.257.575-.574.575h-.004c-.318 0-.575-.258-.575-.575s.258-.575.575-.575h.004zm2.253 0c.318 0 .575.258.575.575s-.258.575-.575.575h-.003c-.318 0-.575-.258-.575-.575s.258-.575.575-.575h.003zM5.26 9.925c.318 0 .575.258.575.575s-.258.575-.575.575h-.01c-.318 0-.575-.258-.575-.575s.258-.575.575-.575h.01zm2.252 0c.317 0 .574.258.574.575s-.257.575-.574.575h-.004c-.318 0-.575-.258-.575-.575s.258-.575.575-.575h.004zm2.25 0c.317 0 .574.258.574.575s-.257.575-.574.575h-.004c-.318 0-.575-.258-.575-.575s.258-.575.575-.575h.004zm2.253 0c.318 0 .575.258.575.575s-.258.575-.575.575h-.003c-.317 0-.575-.258-.575-.575s.258-.575.575-.575h.003zm-.59-4.675v-.925h-4.85v.925c0 .318-.258.575-.575.575s-.575-.258-.575-.575v-.925H4.5c-.245 0-.481.097-.654.271s-.27.409-.27.654v2.425h10.85V5.25c0-.245-.097-.481-.271-.654s-.409-.271-.654-.271h-.925v.925c0 .318-.258.575-.575.575s-.575-.258-.575-.575zm4.15 9c0 .55-.219 1.078-.608 1.467s-.916.608-1.467.608h-9c-.55 0-1.078-.219-1.467-.608s-.608-.916-.608-1.467v-9c0-.55.219-1.078.608-1.467s.916-.608 1.467-.608h.925V2.25c0-.318.258-.575.575-.575s.575.258.575.575v.925h4.85V2.25c0-.318.258-.575.575-.575s.575.258.575.575v.925h.925c.55 0 1.078.219 1.467.608s.608.916.608 1.467v9z"
    />
  </svg>
{/snippet}

{#snippet calendarTrigger()}
  <PopoverTrigger
    type="button"
    disabled={control.disabled}
    aria-label={triggerAriaLabel}
    class={cn(
      buttonVariants({ variant: 'ghost', size: TRIGGER_BUTTON_SIZES[size] }),
      TRIGGER_BUTTON_OVERRIDES[size],
      'text-foreground',
    )}
  >
    {#if triggerIcon}
      {@render triggerIcon()}
    {:else}
      {@render defaultTriggerIcon()}
    {/if}
  </PopoverTrigger>
{/snippet}

{#snippet composedEnd()}
  {@render end?.()}
  {@render calendarTrigger()}
{/snippet}

{#snippet calendarPanel()}
  <Calendar
    {size}
    mode={type}
    selected={current}
    onSelect={handleCalendarSelect}
    month={calendarPlaceholder}
    onMonthChange={handlePlaceholderChange}
    {locale}
    {weekStartsOn}
    startMonth={minValue}
    endMonth={maxValue}
    {fixedWeeks}
    disabled={isDateDisabled}
    {isDateUnavailable}
    {required}
  />
{/snippet}

<Popover open={innerOpen} onOpenChange={setOpen}>
  <div
    data-slot="date-picker"
    data-disabled={control.disabled ? '' : undefined}
    data-invalid={control.invalid ? '' : undefined}
    aria-invalid={control.ariaInvalid}
    aria-disabled={control.disabled || undefined}
    aria-label={ariaLabel}
    aria-labelledby={labelledBy}
    class={cn('flex w-full', className)}
    {...rest}
  >
    {#if type === 'single' && !showTime}
      <DateField
        value={singleDate}
        onValueChange={handleDateFieldChange}
        {variant}
        {size}
        {start}
        end={composedEnd}
        disabled={control.disabled}
        {readonly}
        {required}
        name={control.name}
        granularity="day"
        {locale}
        {minValue}
        {maxValue}
        class={inputClassName}
      />
    {:else if type === 'single' && showTime}
      <div
        data-slot="date-picker-field"
        data-disabled={control.disabled ? '' : undefined}
        data-invalid={control.invalid ? '' : undefined}
        class={wrapperClass}
      >
        {#if start}
          <div data-slot="date-picker-start" class="-ms-1 shrink-0">
            {@render start()}
          </div>
        {/if}
        <DateField unstyled value={singleDate} onValueChange={handleDateFieldChange} {variant} {size} disabled={control.disabled} {readonly} {required} granularity="day" {locale} {minValue} {maxValue} />
        <TimeField
          unstyled
          value={singleDate ? toTimeValue(singleDate) : undefined}
          onValueChange={handleTimeFieldChange}
          {variant}
          {size}
          disabled={control.disabled}
          {readonly}
          {required}
          {locale}
          {hourCycle}
        />
        {#if end}
          <div data-slot="date-picker-end" class="shrink-0">
            {@render end()}
          </div>
        {/if}
        <div data-slot="date-picker-trigger" class="ms-auto -me-1 shrink-0">
          {@render calendarTrigger()}
        </div>
      </div>
    {:else if type === 'range'}
      <div
        data-slot="date-picker-field"
        data-disabled={control.disabled ? '' : undefined}
        data-invalid={control.invalid ? '' : undefined}
        class={wrapperClass}
      >
        {#if start}
          <div data-slot="date-picker-start" class="-ms-1 shrink-0">
            {@render start()}
          </div>
        {/if}
        <DateField
          unstyled
          value={rangeValue?.from}
          onValueChange={handleRangeFromDateChange}
          {variant}
          {size}
          disabled={control.disabled}
          {readonly}
          {required}
          granularity="day"
          {locale}
          {minValue}
          {maxValue}
        />
        {#if showTime}
          <TimeField
            unstyled
            value={rangeValue?.from ? toTimeValue(rangeValue.from) : undefined}
            onValueChange={handleRangeFromTimeChange}
            {variant}
            {size}
            disabled={control.disabled}
            {readonly}
            {required}
            {locale}
            {hourCycle}
          />
        {/if}
        <span class="text-foreground-muted shrink-0" aria-hidden="true">{rangeSeparator}</span>
        <DateField
          unstyled
          value={rangeValue?.to}
          onValueChange={handleRangeToDateChange}
          {variant}
          {size}
          disabled={control.disabled}
          {readonly}
          {required}
          granularity="day"
          {locale}
          {minValue}
          {maxValue}
        />
        {#if showTime}
          <TimeField
            unstyled
            value={rangeValue?.to ? toTimeValue(rangeValue.to) : undefined}
            onValueChange={handleRangeToTimeChange}
            {variant}
            {size}
            disabled={control.disabled}
            {readonly}
            {required}
            {locale}
            {hourCycle}
          />
        {/if}
        {#if end}
          <div data-slot="date-picker-end" class="shrink-0">
            {@render end()}
          </div>
        {/if}
        <div data-slot="date-picker-trigger" class="ms-auto -me-1 shrink-0">
          {@render calendarTrigger()}
        </div>
      </div>
    {:else}
      <Input
        inputSize={size}
        {variant}
        value={multipleDisplay}
        readonly
        {placeholder}
        clearable={clearable && (multipleDays?.length ?? 0) > 0}
        onClear={() => setValue(undefined)}
        {start}
        end={composedEnd}
        disabled={control.disabled}
        {required}
        name={control.name}
        aria-invalid={control.ariaInvalid}
        class={inputClassName}
      />
    {/if}
    {#if emitHidden && type === 'single'}
      <input type="hidden" name={control.name} value={toFormValue(singleDate, showTime)} />
    {:else if emitHidden && type === 'range'}
      <input type="hidden" name={`${control.name}[from]`} value={toFormValue(rangeValue?.from, showTime)} />
      <input type="hidden" name={`${control.name}[to]`} value={toFormValue(rangeValue?.to, showTime)} />
    {/if}
  </div>
  <PopoverContent
    {side}
    {align}
    {sideOffset}
    arrow={false}
    keepMounted={popoverKeepMounted}
    class={cn('w-fit max-w-none min-w-0 p-3', popoverClassName)}
    {...popoverRest}
  >
    {@render calendarPanel()}
  </PopoverContent>
</Popover>
