// playgrounds/svelte/src/app.svelte
<script lang="ts">
  import type { Component } from 'svelte'
  import { Button, useTheme } from '@appica/ui-svelte'
  import AlertScreen from './screens/alert-screen.svelte'
  import AvatarScreen from './screens/avatar-screen.svelte'
  import BackgroundPatternScreen from './screens/background-pattern-screen.svelte'
  import BadgeScreen from './screens/badge-screen.svelte'
  import BorderBeamScreen from './screens/border-beam-screen.svelte'
  import BreadcrumbScreen from './screens/breadcrumb-screen.svelte'
  import ButtonScreen from './screens/button-screen.svelte'
  import ButtonGroupScreen from './screens/button-group-screen.svelte'
  import CardScreen from './screens/card-screen.svelte'
  import CheckboxScreen from './screens/checkbox-screen.svelte'
  import ChipScreen from './screens/chip-screen.svelte'
  import CopyButtonScreen from './screens/copy-button-screen.svelte'
  import CountdownScreen from './screens/countdown-screen.svelte'
  import FieldsetScreen from './screens/fieldset-screen.svelte'
  import FormScreen from './screens/form-screen.svelte'
  import GradientGlowScreen from './screens/gradient-glow-screen.svelte'
  import InputScreen from './screens/input-screen.svelte'
  import KbdScreen from './screens/kbd-screen.svelte'
  import LoaderScreen from './screens/loader-screen.svelte'
  import MeterScreen from './screens/meter-screen.svelte'
  import NavigationScreen from './screens/navigation-screen.svelte'
  import PaginationScreen from './screens/pagination-screen.svelte'
  import PopoverScreen from './screens/popover-screen.svelte'
  import ProgressScreen from './screens/progress-screen.svelte'
  import RadioScreen from './screens/radio-screen.svelte'
  import RatingScreen from './screens/rating-screen.svelte'
  import ScrollAreaScreen from './screens/scroll-area-screen.svelte'
  import SeparatorScreen from './screens/separator-screen.svelte'
  import SkeletonScreen from './screens/skeleton-screen.svelte'
  import SliderScreen from './screens/slider-screen.svelte'
  import SparklineScreen from './screens/sparkline-screen.svelte'
  import SpinnerScreen from './screens/spinner-screen.svelte'
  import SwitchScreen from './screens/switch-screen.svelte'
  import TableScreen from './screens/table-screen.svelte'
  import TextAnimateScreen from './screens/text-animate-screen.svelte'
  import TextareaScreen from './screens/textarea-screen.svelte'
  import ThumbnailScreen from './screens/thumbnail-screen.svelte'
  import TocScreen from './screens/toc-screen.svelte'
  import ToggleScreen from './screens/toggle-screen.svelte'
  import ToolbarScreen from './screens/toolbar-screen.svelte'
  import TooltipScreen from './screens/tooltip-screen.svelte'

  const screens = [
    { id: 'button', label: 'Button' },
    { id: 'button-group', label: 'ButtonGroup' },
    { id: 'badge', label: 'Badge' },
    { id: 'border-beam', label: 'BorderBeam' },
    { id: 'breadcrumb', label: 'Breadcrumb' },
    { id: 'alert', label: 'Alert' },
    { id: 'avatar', label: 'Avatar' },
    { id: 'background-pattern', label: 'BackgroundPattern' },
    { id: 'card', label: 'Card' },
    { id: 'checkbox', label: 'Checkbox' },
    { id: 'chip', label: 'Chip' },
    { id: 'copy-button', label: 'CopyButton' },
    { id: 'countdown', label: 'Countdown' },
    { id: 'fieldset', label: 'Fieldset' },
    { id: 'form', label: 'Form' },
    { id: 'gradient-glow', label: 'GradientGlow' },
    { id: 'input', label: 'Input' },
    { id: 'textarea', label: 'Textarea' },
    { id: 'kbd', label: 'Kbd' },
    { id: 'loader', label: 'Loader' },
    { id: 'meter', label: 'Meter' },
    { id: 'navigation', label: 'Navigation' },
    { id: 'pagination', label: 'Pagination' },
    { id: 'popover', label: 'Popover' },
    { id: 'progress', label: 'Progress' },
    { id: 'radio', label: 'Radio' },
    { id: 'rating', label: 'Rating' },
    { id: 'scroll-area', label: 'ScrollArea' },
    { id: 'separator', label: 'Separator' },
    { id: 'skeleton', label: 'Skeleton' },
    { id: 'slider', label: 'Slider' },
    { id: 'sparkline', label: 'Sparkline' },
    { id: 'spinner', label: 'Spinner' },
    { id: 'switch', label: 'Switch' },
    { id: 'table', label: 'Table' },
    { id: 'text-animate', label: 'TextAnimate' },
    { id: 'thumbnail', label: 'Thumbnail' },
    { id: 'toc', label: 'Toc' },
    { id: 'toggle', label: 'Toggle' },
    { id: 'toolbar', label: 'Toolbar' },
    { id: 'tooltip', label: 'Tooltip' },
  ] as const

  type ScreenId = (typeof screens)[number]['id']

  const views: Record<ScreenId, Component> = {
    button: ButtonScreen,
    'button-group': ButtonGroupScreen,
    badge: BadgeScreen,
    'border-beam': BorderBeamScreen,
    breadcrumb: BreadcrumbScreen,
    alert: AlertScreen,
    avatar: AvatarScreen,
    'background-pattern': BackgroundPatternScreen,
    card: CardScreen,
    checkbox: CheckboxScreen,
    chip: ChipScreen,
    'copy-button': CopyButtonScreen,
    countdown: CountdownScreen,
    fieldset: FieldsetScreen,
    form: FormScreen,
    'gradient-glow': GradientGlowScreen,
    input: InputScreen,
    textarea: TextareaScreen,
    kbd: KbdScreen,
    loader: LoaderScreen,
    meter: MeterScreen,
    navigation: NavigationScreen,
    pagination: PaginationScreen,
    popover: PopoverScreen,
    progress: ProgressScreen,
    radio: RadioScreen,
    rating: RatingScreen,
    'scroll-area': ScrollAreaScreen,
    separator: SeparatorScreen,
    skeleton: SkeletonScreen,
    slider: SliderScreen,
    sparkline: SparklineScreen,
    spinner: SpinnerScreen,
    switch: SwitchScreen,
    table: TableScreen,
    'text-animate': TextAnimateScreen,
    thumbnail: ThumbnailScreen,
    toc: TocScreen,
    toggle: ToggleScreen,
    toolbar: ToolbarScreen,
    tooltip: TooltipScreen,
  }

  let screen: ScreenId = $state('button')
  const theme = useTheme()
  const Screen = $derived(views[screen])

  function toggleTheme() {
    theme.setTheme(theme.resolvedTheme === 'dark' ? 'light' : 'dark')
  }
</script>

<main class="text-foreground bg-background mx-auto flex min-h-dvh max-w-4xl flex-col gap-8 px-6 py-12">
  <header class="flex items-start justify-between gap-4">
    <div>
      <h1 class="text-foreground-intense text-3xl font-semibold">Appica UI Svelte Playground</h1>
      <p class="text-foreground-muted mt-1 text-sm">
        Wave 1 and Wave 2 primitives - edit <code>packages/svelte/src</code> and it hot-reloads.
      </p>
    </div>
    <Button
      variant="outline"
      size="icon-md"
      onclick={toggleTheme}
      aria-label={theme.resolvedTheme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'}
    >
      ◑
    </Button>
  </header>

  <nav class="flex flex-wrap gap-2" aria-label="Component screens">
    {#each screens as item (item.id)}
      <Button variant={screen === item.id ? 'primary' : 'soft'} size="sm" onclick={() => (screen = item.id)}>
        {item.label}
      </Button>
    {/each}
  </nav>

  <Screen />
</main>

// playgrounds/react/src/app.tsx
import { Badge, Button, Input, Switch, Tabs, TabsContent, TabsList, TabsTrigger, useTheme } from '@appica/ui-react'

export function App() {
  const { resolvedTheme, setTheme } = useTheme()

  return (
    <main className="text-foreground bg-background mx-auto flex min-h-dvh max-w-3xl flex-col gap-10 px-6 py-12">
      <header className="flex items-center justify-between">
        <div>
          <h1 className="text-foreground-intense text-3xl font-semibold">Appica UI Playground</h1>
          <p className="text-foreground-muted mt-1 text-sm">
            Scratch page for developing components — edit <code>packages/react/src</code> and it hot-reloads.
          </p>
        </div>
        <Button
          variant="outline"
          size="icon-md"
          onClick={() => setTheme(resolvedTheme === 'dark' ? 'light' : 'dark')}
          aria-label={resolvedTheme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'}
        >
          ◑
        </Button>
      </header>

      <section className="flex flex-col gap-4">
        <h2 className="text-foreground-emphasis text-lg font-semibold">Sandbox</h2>
        <div className="flex flex-wrap items-center gap-3">
          <Button>Primary</Button>
          <Button variant="secondary">Secondary</Button>
          <Button variant="outline">Outline</Button>
          <Button variant="ghost">Ghost</Button>
          <Badge>Badge</Badge>
          <Switch defaultChecked />
        </div>
        <Input placeholder="Type something…" className="max-w-xs" />
        <Tabs defaultValue="one" className="max-w-md">
          <TabsList>
            <TabsTrigger value="one">One</TabsTrigger>
            <TabsTrigger value="two">Two</TabsTrigger>
            <TabsTrigger value="three">Three</TabsTrigger>
          </TabsList>
          <TabsContent value="one">First panel</TabsContent>
          <TabsContent value="two">Second panel</TabsContent>
          <TabsContent value="three">Third panel</TabsContent>
        </Tabs>
      </section>
    </main>
  )
}
