// packages/react/src/components/fieldset/fieldset.tsx
import * as React from 'react'
import { Fieldset as BaseFieldset } from '@base-ui/react/fieldset'
import { cn } from '../../internal/utils'

type FieldsetProps = React.ComponentProps<typeof BaseFieldset.Root>

function Fieldset({ className, ...props }: FieldsetProps) {
  return <BaseFieldset.Root data-slot="fieldset" className={cn('flex w-full flex-col gap-4', className)} {...props} />
}

type FieldsetLegendProps = React.ComponentProps<typeof BaseFieldset.Legend>

function FieldsetLegend({ className, ...props }: FieldsetLegendProps) {
  return (
    <BaseFieldset.Legend
      data-slot="fieldset-legend"
      className={cn('text-foreground-intense text-lg font-medium', className)}
      {...props}
    />
  )
}

export { Fieldset, FieldsetLegend }
export type { FieldsetProps, FieldsetLegendProps }

// packages/svelte/src/components/fieldset/fieldset.svelte
<script lang="ts">
  import type { HTMLFieldsetAttributes } from 'svelte/elements'
  import type { Snippet } from 'svelte'
  import { cn } from '../../internal/utils'

  export type FieldsetProps = HTMLFieldsetAttributes & {
    children?: Snippet
  }

  let { class: className, children, ...rest }: FieldsetProps = $props()
</script>

<fieldset data-slot="fieldset" class={cn('flex w-full flex-col gap-4', className)} {...rest}>
  {@render children?.()}
</fieldset>
