// packages/react/src/components/input/input.tsx
'use client'

import * as React from 'react'
import { Input as BaseInput } from '@base-ui/react/input'
import { type VariantProps } from 'class-variance-authority'
import { cn, useComposedRefs } from '../../utils'
import { inputVariants } from './input-variants'

type InputVariant = NonNullable<VariantProps<typeof inputVariants>['variant']>
type InputSize = NonNullable<VariantProps<typeof inputVariants>['size']>

interface InputProps extends Omit<React.ComponentProps<typeof BaseInput>, 'size'> {
  /**
   * Field appearance - bordered or filled.
   * @default 'outline'
   */
  variant?: InputVariant
  /**
   * Scales height, padding, and text. Named `inputSize` to avoid the native `size` attribute.
   * @default 'md'
   */
  inputSize?: InputSize
  /**
   * Show a clear (✕) button once the field has a value.
   * @default false
   */
  clearable?: boolean
  /** Adornment rendered before the field, inside the frame. */
  startSlot?: React.ReactNode
  /** Adornment rendered after the field, inside the frame. */
  endSlot?: React.ReactNode
  /** Called when the clear button is pressed. */
  onClear?: () => void
  /** Props for the inner `<input>` in wrapper mode (its own `className`, handlers, …). */
  inputProps?: Omit<React.ComponentProps<typeof BaseInput>, 'size'>
}

function setNativeValue(input: HTMLInputElement, value: string) {
  const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')?.set
  setter?.call(input, value)
  input.dispatchEvent(new Event('input', { bubbles: true }))
}

function Input({
  className,
  variant = 'outline',
  inputSize = 'md',
  clearable,
  startSlot,
  endSlot,
  onClear,
  inputProps,
  ref,
  ...props
}: InputProps) {
  const innerRef = React.useRef<HTMLInputElement>(null)
  const hasWrapper = Boolean(clearable || startSlot || endSlot)

  const ariaInvalid = props['aria-invalid']
  const invalid = ariaInvalid === true || ariaInvalid === 'true'

  const composedRef = useComposedRefs(ref, innerRef)

  const handleClear = () => {
    if (innerRef.current && props.value === undefined) {
      setNativeValue(innerRef.current, '')
    }
    innerRef.current?.focus()
    onClear?.()
  }

  if (!hasWrapper) {
    return (
      <BaseInput
        data-slot="input"
        ref={composedRef}
        {...inputProps}
        className={cn(
          inputVariants({ variant, size: inputSize, state: 'self' }),
          'placeholder:text-foreground-subtle',
          inputProps?.className,
          className,
        )}
        {...props}
        {...(invalid ? { 'data-invalid': '' } : {})}
      />
    )
  }

  return (
    <div
      data-slot="input-wrapper"
      className={cn(inputVariants({ variant, size: inputSize, state: 'within' }), className)}
      {...(invalid ? { 'data-invalid': '' } : {})}
    >
      {startSlot && (
        <div data-slot="input-start" className="-ms-1 shrink-0">
          {startSlot}
        </div>
      )}
      <BaseInput
        data-slot="input"
        ref={composedRef}
        placeholder={props.placeholder ?? ' '}
        {...inputProps}
        className={cn(
          'peer text-foreground placeholder:text-foreground-subtle h-full min-w-0 flex-1 bg-transparent outline-none disabled:cursor-not-allowed',
          inputProps?.className,
        )}
        {...props}
      />
      {clearable && (
        <button
          data-slot="input-clear"
          type="button"
          onClick={handleClear}
          className="text-foreground-subtle hover:text-foreground pointer-events-none shrink-0 cursor-pointer opacity-0 transition-[opacity,color] duration-200 peer-not-placeholder-shown:pointer-events-auto peer-not-placeholder-shown:opacity-100"
          tabIndex={-1}
          aria-label="Clear input"
        >
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="2 2 16 16" fill="currentColor" className="size-[1em]">
            <path d="M6.28 5.22a.75.75 0 0 0-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 1 0 1.06 1.06L10 11.06l3.72 3.72a.75.75 0 1 0 1.06-1.06L11.06 10l3.72-3.72a.75.75 0 0 0-1.06-1.06L10 8.94 6.28 5.22Z" />
          </svg>
        </button>
      )}
      {endSlot && (
        <div data-slot="input-end" className="-me-1 shrink-0">
          {endSlot}
        </div>
      )}
    </div>
  )
}

export { Input }
export type { InputProps }

// packages/svelte/src/components/input/input.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from 'svelte/elements'
  import type { Snippet } from 'svelte'
  import type { VariantProps } from 'class-variance-authority'
  import { cn, setNativeValue } from '../../internal/utils'
  import { inputVariants } from './input-variants'

  type InputVariant = NonNullable<VariantProps<typeof inputVariants>['variant']>
  type InputSize = NonNullable<VariantProps<typeof inputVariants>['size']>

  type Props = Omit<HTMLInputAttributes, 'size'> & {
    /**
     * Field appearance - bordered or filled.
     * @default 'outline'
     */
    variant?: InputVariant
    /**
     * Scales height, padding, and text. Named `inputSize` to avoid the native `size` attribute.
     * @default 'md'
     */
    inputSize?: InputSize
    /**
     * Show a clear (✕) button once the field has a value.
     * @default false
     */
    clearable?: boolean
    /** Adornment rendered before the field, inside the frame. */
    start?: Snippet
    /** Adornment rendered after the field, inside the frame. */
    end?: Snippet
    /** Called when the clear button is pressed. */
    onClear?: () => void
    value?: string
  }

  let {
    class: className,
    variant = 'outline',
    inputSize = 'md',
    clearable = false,
    start,
    end,
    onClear,
    value = $bindable(),
    placeholder,
    disabled,
    ...rest
  }: Props = $props()

  let inputEl: HTMLInputElement | undefined = $state()
  const hasWrapper = $derived(Boolean(clearable || start || end))
  const ariaInvalid = $derived(rest['aria-invalid'])
  const invalid = $derived(ariaInvalid === true || ariaInvalid === 'true')

  function handleClear() {
    if (value !== undefined) {
      value = ''
    } else if (inputEl) {
      setNativeValue(inputEl, '')
    }
    inputEl?.focus()
    onClear?.()
  }
</script>

{#if !hasWrapper}
  <input
    bind:this={inputEl}
    bind:value
    data-slot="input"
    data-invalid={invalid ? '' : undefined}
    data-disabled={disabled ? '' : undefined}
    {disabled}
    {placeholder}
    class={cn(inputVariants({ variant, size: inputSize, state: 'self' }), 'placeholder:text-foreground-subtle', className)}
    {...rest}
  />
{:else}
  <div
    data-slot="input-wrapper"
    data-invalid={invalid ? '' : undefined}
    class={cn(inputVariants({ variant, size: inputSize, state: 'within' }), className)}
  >
    {#if start}
      <div data-slot="input-start" class="-ms-1 flex shrink-0 items-center">
        {@render start()}
      </div>
    {/if}
    <input
      bind:this={inputEl}
      bind:value
      data-slot="input"
      {disabled}
      placeholder={placeholder ?? ' '}
      class="peer text-foreground placeholder:text-foreground-subtle h-full min-w-0 flex-1 bg-transparent outline-none disabled:cursor-not-allowed"
      {...rest}
    />
    {#if clearable}
      <button
        data-slot="input-clear"
        type="button"
        onclick={handleClear}
        class="text-foreground-subtle hover:text-foreground pointer-events-none shrink-0 cursor-pointer opacity-0 transition-[opacity,color] duration-200 peer-not-placeholder-shown:pointer-events-auto peer-not-placeholder-shown:opacity-100"
        tabindex={-1}
        aria-label="Clear input"
      >
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="2 2 16 16" fill="currentColor" class="size-[1em]">
          <path
            d="M6.28 5.22a.75.75 0 0 0-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 1 0 1.06 1.06L10 11.06l3.72 3.72a.75.75 0 1 0 1.06-1.06L11.06 10l3.72-3.72a.75.75 0 0 0-1.06-1.06L10 8.94 6.28 5.22Z"
          />
        </svg>
      </button>
    {/if}
    {#if end}
      <div data-slot="input-end" class="-me-1 flex shrink-0 items-center">
        {@render end()}
      </div>
    {/if}
  </div>
{/if}
