// packages/react/src/components/toolbar/toolbar.tsx
import * as React from 'react'
import { Toolbar as BaseToolbar } from '@base-ui/react/toolbar'
import { cn } from '../../internal/utils'

interface ToolbarProps extends React.ComponentProps<typeof BaseToolbar.Root> {}

function Toolbar({ className, ...props }: ToolbarProps) {
  return (
    <BaseToolbar.Root
      data-slot="toolbar"
      className={cn(
        'bg-background flex w-fit items-center gap-1 rounded-lg border p-1',
        'max-h-full max-w-full scrollbar-none overflow-auto *:shrink-0 [&::-webkit-scrollbar]:hidden',
        'data-[orientation=vertical]:flex-col data-[orientation=vertical]:items-stretch',
        className,
      )}
      {...props}
    />
  )
}

interface ToolbarButtonProps extends React.ComponentProps<typeof BaseToolbar.Button> {}

function ToolbarButton(props: ToolbarButtonProps) {
  return <BaseToolbar.Button data-slot="toolbar-button" {...props} />
}

interface ToolbarLinkProps extends React.ComponentProps<typeof BaseToolbar.Link> {}

function ToolbarLink(props: ToolbarLinkProps) {
  return <BaseToolbar.Link data-slot="toolbar-link" {...props} />
}

interface ToolbarInputProps extends React.ComponentProps<typeof BaseToolbar.Input> {}

function ToolbarInput(props: ToolbarInputProps) {
  return <BaseToolbar.Input data-slot="toolbar-input" {...props} />
}

interface ToolbarGroupProps extends React.ComponentProps<typeof BaseToolbar.Group> {}

function ToolbarGroup({ className, ...props }: ToolbarGroupProps) {
  return (
    <BaseToolbar.Group
      data-slot="toolbar-group"
      className={cn('flex items-center gap-1 data-[orientation=vertical]:flex-col', className)}
      {...props}
    />
  )
}

interface ToolbarSeparatorProps extends React.ComponentProps<typeof BaseToolbar.Separator> {}

function ToolbarSeparator({ className, ...props }: ToolbarSeparatorProps) {
  return (
    <BaseToolbar.Separator
      data-slot="toolbar-separator"
      className={cn(
        'bg-border shrink-0',
        'data-[orientation=vertical]:mx-0.5 data-[orientation=vertical]:h-5 data-[orientation=vertical]:w-(--border-width)',
        'data-[orientation=horizontal]:my-0.5 data-[orientation=horizontal]:h-(--border-width) data-[orientation=horizontal]:w-full',
        className,
      )}
      {...props}
    />
  )
}

export { Toolbar, ToolbarButton, ToolbarLink, ToolbarInput, ToolbarGroup, ToolbarSeparator }
export type {
  ToolbarProps,
  ToolbarButtonProps,
  ToolbarLinkProps,
  ToolbarInputProps,
  ToolbarGroupProps,
  ToolbarSeparatorProps,
}

// packages/svelte/src/components/toolbar/toolbar.svelte
<script lang="ts">
  import type { HTMLAttributes } from 'svelte/elements'
  import type { Snippet } from 'svelte'
  import { cn } from '../../internal/utils'
  import { setToolbarContext, ToolbarState, type ToolbarOrientation } from './toolbar-context.svelte'

  type Props = HTMLAttributes<HTMLDivElement> & {
    /**
     * Lay items in a row or a column.
     * @default 'horizontal'
     */
    orientation?: ToolbarOrientation
    /**
     * Disable every item in the toolbar.
     * @default false
     */
    disabled?: boolean
    children?: Snippet
  }

  let {
    class: className,
    orientation = 'horizontal',
    disabled = false,
    children,
    ...rest
  }: Props = $props()

  const ctx = new ToolbarState()
  ctx.getOrientation = () => orientation
  ctx.getDisabled = () => disabled
  setToolbarContext(ctx)

  function handleKeydown(event: KeyboardEvent) {
    if (disabled) return
    const rtl = event.currentTarget instanceof HTMLElement && getComputedStyle(event.currentTarget).direction === 'rtl'
    const vertical = orientation === 'vertical'
    switch (event.key) {
      case 'ArrowRight':
        if (vertical) return
        event.preventDefault()
        ctx.move(rtl ? -1 : 1)
        break
      case 'ArrowLeft':
        if (vertical) return
        event.preventDefault()
        ctx.move(rtl ? 1 : -1)
        break
      case 'ArrowDown':
        event.preventDefault()
        ctx.move(1)
        break
      case 'ArrowUp':
        event.preventDefault()
        ctx.move(-1)
        break
      case 'Home':
        event.preventDefault()
        ctx.focusAt(0)
        break
      case 'End': {
        event.preventDefault()
        const last = ctx.enabled().length - 1
        ctx.focusAt(last)
        break
      }
      default:
        break
    }
  }
</script>

<div
  data-slot="toolbar"
  role="toolbar"
  data-orientation={orientation}
  data-disabled={disabled ? '' : undefined}
  onkeydown={handleKeydown}
  class={cn(
    'bg-background flex w-fit items-center gap-1 rounded-lg border p-1',
    'max-h-full max-w-full scrollbar-none overflow-auto *:shrink-0 [&::-webkit-scrollbar]:hidden',
    'data-[orientation=vertical]:flex-col data-[orientation=vertical]:items-stretch',
    className,
  )}
  {...rest}
>
  {@render children?.()}
</div>
