// packages/svelte/src/components/radio/radio.svelte
<script lang="ts">
  import { RadioGroup as BitsRadioGroup, type WithoutChildrenOrChild } from 'bits-ui'
  import { useReducedMotion } from '../../hooks/use-reduced-motion/use-reduced-motion'
  import { asBitsAttrs, cn, invalidDataAttr } from '../../internal/utils'
  import { getFieldContext, mergeFieldControl } from '../field/field-context'

  const SQUISH_MS = 300
  const SQUISH_EASING = 'cubic-bezier(0.4, 0, 0.2, 1)'

  export type RadioProps = WithoutChildrenOrChild<BitsRadioGroup.ItemProps>

  let {
    class: className,
    value,
    disabled,
    id,
    'aria-invalid': ariaInvalid,
    'aria-describedby': ariaDescribedby,
    ...rest
  }: RadioProps = $props()

  const field = getFieldContext()
  const control = $derived(
    mergeFieldControl({
      field,
      id,
      disabled,
      ariaInvalid,
      ariaDescribedby,
      omitId: true,
    }),
  )

  const reducedMotion = useReducedMotion()
  let rootEl: HTMLElement | null = $state(null)
  let prevChecked: boolean | null = null

  $effect(() => {
    const el = rootEl
    if (!el) return
    const apply = () => squish(el.getAttribute('data-state') === 'checked')
    const observer = new MutationObserver(apply)
    observer.observe(el, { attributes: true, attributeFilter: ['data-state'] })
    apply()
    return () => observer.disconnect()
  })

  const classes = $derived(
    cn(
      'flex size-[1em] min-h-4 min-w-4 shrink-0 cursor-default items-center justify-center',
      'bg-background border-border-strong outline-ring-input rounded-full border outline-offset-1',
      'transition-[background-color,border-color,box-shadow] duration-200 motion-reduce:transition-none',
      'hover:data-[state=unchecked]:not-data-disabled:not-data-invalid:border-border-emphasis',
      'data-[state=checked]:bg-primary data-[state=checked]:outline-ring-primary data-[state=checked]:border-transparent',
      'data-disabled:data-[state=unchecked]:bg-background-subtle data-disabled:data-[state=checked]:opacity-disabled data-disabled:cursor-not-allowed data-disabled:data-[state=unchecked]:border-dashed',
      'data-invalid:border-error data-invalid:data-[state=unchecked]:bg-error-subtle data-invalid:outline-ring-error',
      className,
    ),
  )

  function squish(isChecked: boolean) {
    const el = rootEl
    const reduced = reducedMotion.current
    if (prevChecked === null) {
      prevChecked = isChecked
      return
    }
    const toggled = prevChecked !== isChecked
    prevChecked = isChecked
    if (toggled && !reduced && el) {
      el.animate([{ scale: '1' }, { scale: '0.8' }, { scale: '1.1' }, { scale: '1' }], {
        duration: SQUISH_MS,
        easing: SQUISH_EASING,
      })
    }
  }
</script>

<BitsRadioGroup.Item
  bind:ref={rootEl}
  data-slot="radio"
  class={classes}
  {value}
  disabled={control.disabled}
  id={control.id}
  aria-invalid={control.ariaInvalid}
  aria-describedby={control.describedby}
  {...asBitsAttrs(rest)}
  {...invalidDataAttr(control.ariaInvalid)}
>
  {#snippet children({ checked })}
    {@const reduced = reducedMotion.current}
    <span data-slot="radio-indicator" class="flex items-center justify-center">
      <span
        class="bg-primary-foreground size-[0.5em] min-h-2 min-w-2 rounded-full"
        style:transform={checked ? 'scale(1)' : 'scale(0)'}
        style:transition={reduced ? 'none' : 'transform 0.3s cubic-bezier(0.4, 0, 0.2, 1)'}
      ></span>
    </span>
  {/snippet}
</BitsRadioGroup.Item>

// packages/react/src/components/radio/radio.tsx
'use client'

import * as React from 'react'
import { Radio as BaseRadio } from '@base-ui/react/radio'
import { LazyMotion, domAnimation, m, useAnimate } from 'motion/react'
import { useReducedMotion } from '../../hooks/use-reduced-motion'
import { cn, useComposedRefs } from '../../internal/utils'

const SQUISH_TRANSITION = {
  duration: 0.3,
  ease: [0.4, 0, 0.2, 1] satisfies [number, number, number, number],
}

const INDICATOR_TRANSITION = {
  duration: 0.3,
  ease: [0.4, 0, 0.2, 1] satisfies [number, number, number, number],
}

const ZERO_TRANSITION = { duration: 0 } as const

function RadioIndicator({ checked, reduced }: { checked: boolean; reduced: boolean }) {
  return (
    <BaseRadio.Indicator data-slot="radio-indicator" className="flex items-center justify-center" keepMounted>
      <m.span
        className="bg-primary-foreground size-[0.5em] min-h-2 min-w-2 rounded-full"
        initial={false}
        animate={{ scale: checked ? 1 : 0 }}
        transition={reduced ? ZERO_TRANSITION : INDICATOR_TRANSITION}
      />
    </BaseRadio.Indicator>
  )
}

function RadioRoot({
  renderProps,
  state,
  reduced,
}: {
  renderProps: React.ComponentPropsWithRef<'span'>
  state: { checked: boolean }
  reduced: boolean
}) {
  const { checked } = state
  const { ref, ...htmlProps } = renderProps
  const [scope, animate] = useAnimate()
  const composedRef = useComposedRefs(ref, scope)

  const prevChecked = React.useRef(checked)
  React.useEffect(() => {
    const toggled = prevChecked.current !== checked
    prevChecked.current = checked
    if (toggled && !reduced) {
      animate(scope.current, { scale: [1, 0.8, 1.1, 1] }, SQUISH_TRANSITION)
    }
  }, [checked, animate, scope, reduced])

  return (
    <span data-slot="radio" {...htmlProps} ref={composedRef}>
      <RadioIndicator checked={checked} reduced={reduced} />
    </span>
  )
}

type RadioProps = React.ComponentProps<typeof BaseRadio.Root>

function Radio({ className, ...props }: RadioProps) {
  const reduced = useReducedMotion()

  const ariaInvalid = props['aria-invalid']
  const invalid = ariaInvalid === true || ariaInvalid === 'true'

  return (
    <LazyMotion features={domAnimation} strict>
      <BaseRadio.Root
        {...props}
        {...(invalid ? { 'data-invalid': '' } : {})}
        className={cn(
          'flex size-[1em] min-h-4 min-w-4 shrink-0 cursor-default items-center justify-center',
          'bg-background border-border-strong outline-ring-input rounded-full border outline-offset-1',
          'transition-[background-color,border-color,box-shadow] duration-200 motion-reduce:transition-none',
          'hover:not-data-checked:not-data-disabled:not-data-invalid:border-border-emphasis',
          'data-checked:bg-primary data-checked:outline-ring-primary data-checked:border-transparent',
          'data-disabled:not-data-checked:bg-background-subtle data-disabled:data-checked:opacity-disabled data-disabled:cursor-not-allowed data-disabled:not-data-checked:border-dashed',
          'data-invalid:border-error data-invalid:not-data-checked:bg-error-subtle data-invalid:outline-ring-error',
          className,
        )}
        render={(renderProps, state) => <RadioRoot renderProps={renderProps} state={state} reduced={reduced} />}
      />
    </LazyMotion>
  )
}

export { Radio }
export type { RadioProps }
