// packages/react/src/components/radio-group/radio-group.tsx
import * as React from 'react'
import { RadioGroup as BaseRadioGroup } from '@base-ui/react/radio-group'
import { cn } from '../../internal/utils'

interface RadioGroupProps extends React.ComponentProps<typeof BaseRadioGroup> {
  /**
   * Lay options out in a row or column; sets which arrow keys move selection.
   * @default 'vertical'
   */
  orientation?: 'horizontal' | 'vertical'
}

function RadioGroup({ className, orientation = 'vertical', ...props }: RadioGroupProps) {
  const horizontal = orientation === 'horizontal'
  return (
    <BaseRadioGroup
      data-slot="radio-group"
      aria-orientation={orientation}
      className={cn('flex', horizontal ? 'flex-wrap gap-4' : 'flex-col gap-2', className)}
      {...props}
    />
  )
}

export { RadioGroup }
export type { RadioGroupProps }

// packages/svelte/src/components/radio-group/radio-group.svelte
<script lang="ts">
  import type { HTMLAttributes } from 'svelte/elements'
  import type { Snippet } from 'svelte'
  import { untrack } from 'svelte'
  import { RadioGroup as BitsRadioGroup } from 'bits-ui'
  import { asBitsAttrs, cn, commitBindableChange } from '../../internal/utils'

  type Props = HTMLAttributes<HTMLDivElement> & {
    /** Controlled selected value. Pair with `onValueChange` or `bind:value`. */
    value?: string
    /**
     * Uncontrolled initial selected value.
     * @default ''
     */
    defaultValue?: string
    /** Fires when the selected value changes. */
    onValueChange?: (value: string) => void
    /**
     * Lay options out in a row or column; sets which arrow keys move selection.
     * @default 'vertical'
     */
    orientation?: 'horizontal' | 'vertical'
    /** Field name submitted with a form. */
    name?: string
    /**
     * Disable every radio in the group.
     * @default false
     */
    disabled?: boolean
    children?: Snippet
  }

  let {
    class: className,
    value = $bindable(),
    defaultValue = '',
    onValueChange,
    orientation = 'vertical',
    name,
    disabled,
    children,
    ...rest
  }: Props = $props()

  let inner = $state('')
  inner = untrack(() => value ?? defaultValue)
  const horizontal = $derived(orientation === 'horizontal')
  const classes = $derived(cn('flex', horizontal ? 'flex-wrap gap-4' : 'flex-col gap-2', className))

  $effect(() => {
    if (value !== undefined) inner = value
  })

  function handleValueChange(next: string) {
    commitBindableChange({
      next,
      bound: value,
      setBound: (nextValue) => {
        value = nextValue
      },
      setInner: (nextValue) => {
        inner = nextValue
      },
      onChange: onValueChange,
    })
  }
</script>

<BitsRadioGroup.Root
  data-slot="radio-group"
  class={classes}
  bind:value={inner}
  {orientation}
  {name}
  {disabled}
  aria-orientation={orientation}
  onValueChange={handleValueChange}
  {...asBitsAttrs(rest)}
>
  {@render children?.()}
</BitsRadioGroup.Root>
